# Generated by Django 6.0 on 2026-01-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_comment_alter_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seating_type',
            field=models.CharField(choices=[('counter', 'Omakase Counter (Live Chef)'), ('table', 'Regular Table'), ('private', 'Private Room (Tatami)')], default='table', max_length=10),
        ),
    ]
