# Generated by Django 6.0 on 2026-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking_seating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seating_type',
            field=models.CharField(choices=[('counter', 'Omakase Counter (Depan Chef)'), ('private', 'Private Tatami Room'), ('table', 'Regular Table')], default='table', max_length=20),
        ),
    ]
